# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New York Times' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New York Times

   pod 'Alamofire', '4.9.1'
   pod 'Kingfisher'
   pod 'ObjectMapper', '~> 3.4'
   pod 'SwiftyJSON'
   pod 'SkeletonView'
   pod 'NVActivityIndicatorView'
   pod 'UIScrollView-InfiniteScroll'

  target 'New York TimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'New York TimesUITests' do
    # Pods for testing
  end

end
